version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alo
      POSTGRES_PASSWORD: suserar
      POSTGRES_DB: nestdb
    ports:
      - 5432:5432